### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by MSchellenberger** [soledadgcogno/Ultraslow-oscillatory-sequences#1]
Hi @soledadgcogno ,

Thanks for sharing the code used for your ultraslow oscillatory sequences paper on github! I am currently working through your convincing findings and wanted to dig a bit deeper into the analysis, as well as the dataset and noticed that you did not add a license yet, making the code your exclusive copyright by default. Thus, it would be greatly appreciated if you could add a license.
Thanks a lot in advance!

**Comment by simon-ball** [comment]
I have added the MIT licence to the repository. 

Thanks for pointing the error out!

**Comment by MSchellenberger** [comment]
Thank you!
